// desk/src/pages/auth/Login.vue
<template>
	<LoginBox v-if="!successMessage" title="Login to your account">
		<form class="space-y-4" @submit.prevent="login">
			<Input
				v-model="email"
				class="rounded-xl"
				required
				:type="email !== 'Administrator' ? 'email' : 'text'"
				placeholder="Email"
			/>
			<Input
				v-model="password"
				class="rounded-xl"
				type="password"
				placeholder="Password"
				name="password"
				autocomplete="current-password"
				required
			/>
			<ErrorMessage :message="errorMessage" />
			<Button
				class="w-full rounded-xl bg-gray-900 text-white hover:bg-gray-800"
				label="Login"
				:disabled="state === 'RequestStarted'"
				type="primary"
				@click="login"
			/>
			<div>
				<div class="mt-8 border-t text-center">
					<div class="-translate-y-1/2">
						<span class="bg-white px-2 text-xs tracking-wider text-gray-700">
							OR
						</span>
					</div>
				</div>
				<router-link
					class="text-center text-base"
					:to="`${$route.name === 'DeskLogin' ? '' : ''}/signup`"
				>
					<div>Sign up for a new account</div>
				</router-link>
			</div>
		</form>
	</LoginBox>
	<SuccessCard v-else class="mx-auto mt-20" title="Password Reset Link Sent.">
		We have sent an email to <span class="font-semibold">{{ email }}</span
		>. Please click on the link received to reset your password.
	</SuccessCard>
</template>

<script>
import { ref } from "vue";
import { ErrorMessage, Input } from "frappe-ui";
import { useAuthStore } from "@/stores/auth";
import LoginBox from "@/components/global/LoginBox.vue";
import SuccessCard from "@/components/global/SuccessCard.vue";

export default {
	name: "Login",
	components: {
		ErrorMessage,
		Input,
		LoginBox,
		SuccessCard,
	},
	setup() {
		const authStore = useAuthStore();
		const state = ref(null); // Idle, Logging In, Login Error
		const email = ref(null);
		const password = ref(null);
		const errorMessage = ref(null);
		const successMessage = ref(null);

		return {
			authStore,
			email,
			errorMessage,
			password,
			state,
			successMessage,
		};
	},
	methods: {
		async login() {
			if (!this.email || !this.password) return;

			this.errorMessage = null;
			this.state = "RequestStarted";

			await this.authStore
				.login(this.email, this.password)
				.catch((error) => (this.errorMessage = error.message))
				.finally(() => (this.state = null));
		},
	},
};
</script>

// desk-react/src/pages/Login.tsx
import { useState, FormEvent } from 'react';
import { useAuthStore } from '@/stores/authStore';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card } from '@/components/ui/card';

export function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const { login } = useAuthStore();

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setError('');
    setIsLoading(true);

    try {
      await login(email, password);
      window.location.href = '/';
    } catch (err: any) {
      setError(err.response?.data?.error || 'Invalid credentials');
      setIsLoading(false);
    }
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-50">
      <Card className="w-full max-w-md p-8">
        <div className="text-center mb-8">
          <h1 className="text-2xl font-bold">Helpdesk Login</h1>
          <p className="text-gray-600 mt-2">Sign in to your account</p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          {error && (
            <div className="bg-red-50 text-red-600 p-3 rounded-md text-sm">
              {error}
            </div>
          )}

          <div>
            <label htmlFor="email" className="block text-sm font-medium mb-1">
              Email
            </label>
            <Input
              id="email"
              name="email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              placeholder="Enter your email"
            />
          </div>

          <div>
            <label htmlFor="password" className="block text-sm font-medium mb-1">
              Password
            </label>
            <Input
              id="password"
              name="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              placeholder="Enter your password"
            />
          </div>

          <Button type="submit" className="w-full" disabled={isLoading}>
            {isLoading ? 'Signing in...' : 'Sign In'}
          </Button>

          <div className="text-center text-sm">
            <span className="text-gray-600">Don't have an account? </span>
            <a href="/register" className="text-primary hover:underline">
              Sign up
            </a>
          </div>
        </form>
      </Card>
    </div>
  );
}
